# config/thresholds.yaml

# Distance thresholds (in meters) for vehicle actions
brake_distance: 5.0      # Distance within which vehicle must brake immediately
slowdown_distance: 15.0  # Distance within which vehicle should slow down
reroute_distance: 25.0   # Distance within which vehicle should reroute
