# config/v2v_settings.yaml

# V2V Communication Settings
latency_ms: 50         # Artificial latency in milliseconds
packet_loss: 0.01      # Simulated packet loss probability (1%)

# Encryption settings
encryption:
  enabled: true
  algorithm: AES
  key: "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI="
  # ✅ Valid base64 string (32-byte AES-256 key)
  mode: CBC
