# config/v2v_settings.yaml

encryption:
  enabled: true
  method: "AES"
  key_size: 256

communication:
  buffer_size: 4096
  timeout: 1.0

logging:
  enabled: true
  level: "INFO"

vehicle_behavior:
  max_speed: 30.0
  acceleration: 3.0
  deceleration: 5.0
